name: os
description: My custom secureblue image
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest
modules:
  - type: files
    files:
      - usr: /usr
  - type: script
    snippets:
      - "ln -s /var/home/r /r"
      - "ln -s /var/home/r/da /da"
      - "ln -s /var/home/r/o /o"
      - "ln -s /var/home/r/dup /dup"
      - "ln -s /var/home/r/repos /repos"
